# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: '2'

volumes:
  sentry-main-data:
    external: true
  sentry-postgres-data:
    external: true

services:
  base:
    build: .
    env_file: ./.env
    environment:
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - sentry-main-data:/var/lib/sentry/files

  smtp:
    image: tianon/exim4

  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.2-alpine

  postgres:
    image: postgres:9.5
    volumes:
      - sentry-postgres-data:/var/lib/postgresql/data

  web:
    extends: base
    links:
      - redis
      - postgres
      - memcached
      - smtp
    ports:
      - '9000:9000'

  cron:
    extends: base
    command: run cron
    links:
      - redis
      - postgres
      - memcached
      - smtp

  worker:
    extends: base
    command: run worker
    links:
      - redis
      - postgres
      - memcached
      - smtp
